set(_CATKIN_CURRENT_PACKAGE "laser_scan_intro")
set(laser_scan_intro_VERSION "0.0.0")
set(laser_scan_intro_MAINTAINER "justin <justin@todo.todo>")
set(laser_scan_intro_PACKAGE_FORMAT "2")
set(laser_scan_intro_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf" "laser_geometry")
set(laser_scan_intro_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf" "laser_geometry")
set(laser_scan_intro_BUILDTOOL_DEPENDS "catkin")
set(laser_scan_intro_BUILDTOOL_EXPORT_DEPENDS )
set(laser_scan_intro_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf" "laser_geometry")
set(laser_scan_intro_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf" "laser_geometry")
set(laser_scan_intro_TEST_DEPENDS )
set(laser_scan_intro_DOC_DEPENDS )
set(laser_scan_intro_URL_WEBSITE "")
set(laser_scan_intro_URL_BUGTRACKER "")
set(laser_scan_intro_URL_REPOSITORY "")
set(laser_scan_intro_DEPRECATED "")