set(_CATKIN_CURRENT_PACKAGE "fake_point_cloud")
set(fake_point_cloud_VERSION "0.0.0")
set(fake_point_cloud_MAINTAINER "justin <justin@todo.todo>")
set(fake_point_cloud_PACKAGE_FORMAT "2")
set(fake_point_cloud_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf")
set(fake_point_cloud_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf")
set(fake_point_cloud_BUILDTOOL_DEPENDS "catkin")
set(fake_point_cloud_BUILDTOOL_EXPORT_DEPENDS )
set(fake_point_cloud_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf")
set(fake_point_cloud_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf")
set(fake_point_cloud_TEST_DEPENDS )
set(fake_point_cloud_DOC_DEPENDS )
set(fake_point_cloud_URL_WEBSITE "")
set(fake_point_cloud_URL_BUGTRACKER "")
set(fake_point_cloud_URL_REPOSITORY "")
set(fake_point_cloud_DEPRECATED "")