set(_CATKIN_CURRENT_PACKAGE "learning_odom")
set(learning_odom_VERSION "0.0.0")
set(learning_odom_MAINTAINER "justin <justin@todo.todo>")
set(learning_odom_PACKAGE_FORMAT "2")
set(learning_odom_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "tf")
set(learning_odom_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "tf")
set(learning_odom_BUILDTOOL_DEPENDS "catkin")
set(learning_odom_BUILDTOOL_EXPORT_DEPENDS )
set(learning_odom_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "tf")
set(learning_odom_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "tf")
set(learning_odom_TEST_DEPENDS )
set(learning_odom_DOC_DEPENDS )
set(learning_odom_URL_WEBSITE "")
set(learning_odom_URL_BUGTRACKER "")
set(learning_odom_URL_REPOSITORY "")
set(learning_odom_DEPRECATED "")